apiVersion: v1
kind: Service
metadata:
  name: lifelog-postgres
spec:
  clusterIP: None
  selector:
    app: lifelog-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
